### ISSUE TITLE
GNOME Runtime 43/44 EOL

### ISSUE THREAD

**Issue by yakushabb** [flathub/com.kavilgroup.gelectrical#22]
GNOME 43 and 44 runtimes have reached end-of-life and are no longer supported.

I tried to build gelectrical with runtime 46, but there was some errors. Could you update the runtime to a supported version?

Thanks.

**Comment by manuvarkey** [comment]
It seems to be due to change in python version used in the runtime. Some binary python packages are being used by the application. I am in the process of updating other dependencies. Needs to make some changes due to API changes. Will update soon.

Thanks for the interest.

**Comment by manuvarkey** [comment]
Updated to runtime 46
